from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.classification_rule import ClassificationRule
from app.models.enums import PatternType

DEFAULT_RULES: list[dict] = [
    {
        "name": "Amazon transactions",
        "pattern": "amazon",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "amazon_transaction",
        "requires_invoice": False,
        "priority": 200,
        "confidence": Decimal("0.9"),
    },
    {
        "name": "Amazon AMZN prefix",
        "pattern": "amzn",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "amazon_transaction",
        "requires_invoice": False,
        "priority": 200,
        "confidence": Decimal("0.9"),
    },
    {
        "name": "Amazon seller repayment",
        "pattern": "seller repayment",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "amazon_transaction",
        "requires_invoice": False,
        "priority": 200,
        "confidence": Decimal("0.9"),
    },
    {
        "name": "Amazon FBA",
        "pattern": "fba",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "amazon_transaction",
        "requires_invoice": False,
        "priority": 190,
        "confidence": Decimal("0.85"),
    },
    {
        "name": "Amazon marketplace",
        "pattern": "amazon marketplace",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "amazon_transaction",
        "requires_invoice": False,
        "priority": 200,
        "confidence": Decimal("0.9"),
    },
    {
        "name": "Bank fees",
        "pattern": "bank fee",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "bank_fee",
        "requires_invoice": False,
        "priority": 180,
        "confidence": Decimal("0.85"),
    },
    {
        "name": "Monthly fee",
        "pattern": "monthly fee",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "bank_fee",
        "requires_invoice": False,
        "priority": 180,
        "confidence": Decimal("0.85"),
    },
    {
        "name": "Service charge",
        "pattern": "service charge",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "bank_fee",
        "requires_invoice": False,
        "priority": 180,
        "confidence": Decimal("0.85"),
    },
    {
        "name": "Non-sterling fee",
        "pattern": "non-sterling",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "bank_fee",
        "requires_invoice": False,
        "priority": 180,
        "confidence": Decimal("0.85"),
    },
    {
        "name": "Annual fee",
        "pattern": "annual fee",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "bank_fee",
        "requires_invoice": False,
        "priority": 180,
        "confidence": Decimal("0.85"),
    },
    {
        "name": "Revolut business fee",
        "pattern": "revolut business fee",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "bank_fee",
        "requires_invoice": False,
        "priority": 180,
        "confidence": Decimal("0.85"),
    },
    {
        "name": "Internal transfer",
        "pattern": "internal transfer",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "internal_transfer",
        "requires_invoice": False,
        "priority": 170,
        "confidence": Decimal("0.8"),
    },
    {
        "name": "Transfer keyword",
        "pattern": "intercompany",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "internal_transfer",
        "requires_invoice": False,
        "priority": 160,
        "confidence": Decimal("0.75"),
    },
    {
        "name": "Salary payments",
        "pattern": "salary",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "salary",
        "requires_invoice": False,
        "priority": 150,
        "confidence": Decimal("0.9"),
    },
    {
        "name": "Stripe revenue",
        "pattern": "stripe payments",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "revenue",
        "requires_invoice": False,
        "priority": 150,
        "confidence": Decimal("0.85"),
    },
    {
        "name": "Google software",
        "pattern": "google",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "software_subscription",
        "requires_invoice": True,
        "invoice_provider": "merchant_name",
        "priority": 140,
        "confidence": Decimal("0.75"),
    },
    {
        "name": "Meta ads",
        "pattern": "meta",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "software_subscription",
        "requires_invoice": True,
        "invoice_provider": "merchant_name",
        "priority": 140,
        "confidence": Decimal("0.75"),
    },
    {
        "name": "Facebook",
        "pattern": "facebook",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "software_subscription",
        "requires_invoice": True,
        "invoice_provider": "merchant_name",
        "priority": 140,
        "confidence": Decimal("0.75"),
    },
    {
        "name": "Adobe",
        "pattern": "adobe",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "software_subscription",
        "requires_invoice": True,
        "invoice_provider": "merchant_name",
        "priority": 140,
        "confidence": Decimal("0.75"),
    },
    {
        "name": "Notion",
        "pattern": "notion",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "software_subscription",
        "requires_invoice": True,
        "invoice_provider": "merchant_name",
        "priority": 140,
        "confidence": Decimal("0.75"),
    },
    {
        "name": "OpenAI",
        "pattern": "openai",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "software_subscription",
        "requires_invoice": True,
        "invoice_provider": "merchant_name",
        "priority": 140,
        "confidence": Decimal("0.75"),
    },
    {
        "name": "Logistics forwarder",
        "pattern": "freight",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "logistics",
        "requires_invoice": True,
        "invoice_provider": "merchant_name",
        "priority": 130,
        "confidence": Decimal("0.7"),
    },
    {
        "name": "Fulfillment",
        "pattern": "fulfillment",
        "pattern_type": PatternType.CONTAINS.value,
        "category": "logistics",
        "requires_invoice": True,
        "invoice_provider": "merchant_name",
        "priority": 130,
        "confidence": Decimal("0.7"),
    },
]


async def seed_default_rules(session: AsyncSession) -> int:
    result = await session.execute(select(ClassificationRule).limit(1))
    if result.scalar_one_or_none():
        return 0

    for rule_data in DEFAULT_RULES:
        session.add(ClassificationRule(**rule_data))
    await session.commit()
    return len(DEFAULT_RULES)
